apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: compare-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  labels:
    name: compare-app-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: backend.customer
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 80

    - host: frontend.customer
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80

