pipeline {
    agent any

    environment {
        KUBECONFIG_CREDENTIALS = credentials('kubernetes') // Kubeconfig enregistré dans Jenkins
    }

    stages {
        stage('Déployer MySQL') {
            steps {
                withKubeConfig([credentialsId: 'kubernetes']) {
                    sh '''
                    kubectl apply -f K8S/mysql-pv.yaml
                    kubectl apply -f K8S/mysql-pvc.yaml
                    kubectl apply -f K8S/mysql-deployment.yaml
                    kubectl rollout status deployment/mysql
                    '''
                }
            }
        }

}
}
